#pre-configuraciones
[pytest]

python_files = test_*.py #todos los archivos q empiecen con test_ se van a ejecutar cuando se ejecute pytest

python_functions = test_*

#párametro para los reportes HTML
# self-contained -- los estilos de la pag se hacen desde el mismo archivo html
addopts= -v -s --html=reports/reporte.html --self-contained-html 